#
# MADE BY: AnonymouslyFast (Caleb)
#
# Below is the configuration for the bot
# If the '' is empty it need a input
# please do not change anything unless needed
#

# Minecraft
server-ip: ''
server-name: ''

# Discord
bot-token: ''
minecraft-to-discord-channel-id: ''
minecraft-logs-channel-id: ''
discord-verification-channel-id: ''
discord-verified-role-id: ''
guild-id: ''

# Economy
starting-balance: 500.0
economy-prefix: '2&l[&a&lEconomy&2&l]'
# Delay for saving (in minutes)
# Have to restart if changed, can't use reload command for this.
economy-saves-accounts-every: 10

# DataBase
db-username: ''
db-password: ''
# The Data base template is:
#  jdbc:sqlserver://ServerName:Port;databaseName=;user=username;password=password;
db-url: ''
